apiVersion: v1
kind: Service
metadata:
  name: lifters-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: lifters
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
